import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import '../globals.css'
import ThemeProvider from '@/app/_components/providers/ThemeProvider'
import Header from '@/app/_components/Header'
import { ReactNode } from 'react'
import { SiteLanguage } from '@/app/config/site.config'
import { Toaster } from '@/components/ui/sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
  title: {
    template: '%s | Access Control',
    default: 'Access Control',
  },
  description: 'Generated by create next app',
}

export default async function RootLayout({
                                           children,
                                           params,
                                         }: Readonly<{
  children: ReactNode
  params: Promise<{ lang: SiteLanguage }>
}>) {
  const locale = await params

  return (
    <html
      lang={locale.lang}
      suppressHydrationWarning
    >
    <body
      className={`${geistSans.variable} antialiased`}
    >
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <Header params={params} />
      {children}
      <Toaster
        richColors={true}
        closeButton={true}
        position="top-right"
      />
    </ThemeProvider>
    </body>
    </html>
  )
}
